CREATE TABLE `game_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`appid` int NOT NULL,
	`name` varchar(512) NOT NULL,
	`developer` text,
	`publisher` text,
	`genre` text,
	`tags` json,
	`header_image` text,
	`capsule_image` text,
	`price_usd` float,
	`original_price_usd` float,
	`discount_percent` int DEFAULT 0,
	`is_free` int DEFAULT 0,
	`release_date` varchar(64),
	`review_score` int DEFAULT 0,
	`review_score_desc` varchar(128),
	`total_reviews` int DEFAULT 0,
	`positive_reviews` int DEFAULT 0,
	`negative_reviews` int DEFAULT 0,
	`metacritic_score` int,
	`short_description` text,
	`website` text,
	`platforms` json,
	`screenshots` json,
	`background` text,
	`current_players` int DEFAULT 0,
	`peak_players` int DEFAULT 0,
	`peak_players_all_time` int DEFAULT 0,
	`average_playtime_forever` int DEFAULT 0,
	`average_playtime_2weeks` int DEFAULT 0,
	`owners_min` bigint DEFAULT 0,
	`owners_max` bigint DEFAULT 0,
	`ccu` int DEFAULT 0,
	`score_rank` varchar(32),
	`last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `game_cache_id` PRIMARY KEY(`id`),
	CONSTRAINT `game_cache_appid_unique` UNIQUE(`appid`)
);
--> statement-breakpoint
CREATE TABLE `player_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`appid` int NOT NULL,
	`players` int NOT NULL,
	`recorded_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `player_history_id` PRIMARY KEY(`id`)
);
